name: 'Hello World'
description: 'Greet someone'
inputs:
  test_input:
    description: 'Test input'
    required: true
runs:
  using: "composite"
  steps:
    - name: Verify input and ENV
      run: |
        if [[ ${{ inputs.test_input }} == 1 ]]; then
          echo "Input OK"
        else
          echo "Bad input" && exit 1
        fi
        
        if [[ $LARGER_THAN_0 == 1 ]]; then
          echo "Environment variable OK"
        else
          echo "Bad environment variable"
        fi
      shell: bash
    - name: Test shell
      run: print("Test shell OK")
      shell: python
    - name: Set up test
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Run test
      run: test2.sh
      shell: bash
